:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    mark_cart_as_abandoned_job:
      cron: "0 * * * *"
      class: "MarkCartAsAbandonedJob"
      queue: default
      description: "Marks carts as abandoned if they have been inactive for more than 3 hours and deletes carts abandoned for more than 7 days"
